name: aita-judge
channels:
  - conda-forge
dependencies:
  # C dependencies
  - python>=3.8
  - ffmpeg

  # Python dependencies (should match requirements.txt)
  - openai
  - python-dotenv
  - praw
  - requests
  - pandas
  - gtts
  - tqdm
  - scikit-learn
  - ffmpeg-python
  - Pillow

  # conda version of selenium doesn't automatically download chrome drivers
  # for some reason. at least on my machine. revert to pip version I guess.
  - pip
  - pip:
     - selenium
